services:
  - type: web
    name: ai-model-backend
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: SUPABASE_URL
        value: https://hrmwenjncgrqvfaoawep.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybXdlbmpuY2dycXZmYW9hd2VwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzE5ODI0OSwiZXhwIjoyMDYyNzc0MjQ5fQ.Fq8fawVCRRBPaOF-1gcUAornIk7VMbe2EFfrDS3Wquk
      - key: SUPABASE_BUCKET
        value: incident-uploads
